server:
  port: 9000

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
          ###################################################################################
          ##########################  api-auth  #####################################
          - id: auth-main
            uri: http://localhost:9001
            predicates:
              - Path=/auth
            filters:
              - RewritePath=/auth, /api/v1/auth

          - id: auth
            uri: http://localhost:9001
            predicates:
              - Path=/auth/**
            filters:
              - RewritePath=/auth/(?<remaining>.*), /api/v1/auth/${remaining}

          ###################################################################################
          ##########################  api-booking  #####################################
          - id: booking-main
            uri: http://localhost:9002
            predicates:
              - Path=/bookings
            filters:
              - RewritePath=/bookings, /api/v1/bookings

          - id: booking
            uri: http://localhost:9002
            predicates:
              - Path=/bookings/**
            filters:
              - RewritePath=/bookings/(?<remaining>.*), /api/v1/bookings/${remaining}


